version: "3.9"

services:
  # neo4j:
  #   image: neo4j:5.11
  #   container_name: neo4j
  #   ports:
  #     - "7474:7474"
  #     - "7687:7687"
  #   environment:
  #     - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -s http://localhost:7474 || exit 1"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 5
  #   networks:
  #     - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: chatbot
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend

  server:
    build:
      context: .
    container_name: chatbot1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy
      # neo4j:
      #   condition: service_healthy
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend: